version: "3.8"
services:
  # Application
  app:
    build:
      context: ./docker/services/app
      dockerfile: app.dockerfile
    working_dir: /var/www
    env_file: .env
    volumes:
      - ./:/var/www
    networks:
      - hotel-provider-system

  # Web Server
  web:
    build:
      context: ./docker/services/web
      dockerfile: web.dockerfile
    working_dir: /var/www
    env_file: .env
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - "8081:80"
    networks:
      - hotel-provider-system

  # Database
  database:
    image: mysql:8.0.25
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hotel-provider-system-db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_TCP_PORT: 3307
      # MYSQL_USER: secret
      # MYSQL_PASSWORD: secret
    ports:
      - "3307:3307"
    env_file: .env
    networks:
      - hotel-provider-system

  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./:/var/www
      - .env:/var/www/.env
    ports:
      - 8081:80
    env_file: .env
    working_dir: /var/www
    profiles: ["npm"]
    entrypoint: ["npm"]
    networks:
      - hotel-provider-system

networks:
  hotel-provider-system:
    name: "hotel-provider-system-network"